apiVersion: apps/v1
kind: Deployment
metadata:
   name: nextfit-pod
   labels:
      app: nextfit
spec:
   selector:
      matchLabels:
         app: nextfit
   template:
      metadata:
         labels:
            app: nextfit
      spec:
         containers:
         - name: nextfit
           image: timomittermayr/backend:latest
           imagePullPolicy: Always
           ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nextfit-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: nextfit