apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextfit-quarkus
  labels:
    app: nextfit
  namespace: student-t-mittermayr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextfit
  template:
    metadata:
      labels:
        app: nextfit
    spec:
      containers:
        - name: nextfit-backend
          image: timomittermayr/nextfit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.2"
            requests:
              memory: "500Mi"
              cpu: "0.1"
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: demo
            - name: QUARKUS_DATASOURCE_USERNAME
              value: demo
---
apiVersion: v1
kind: Service
metadata:
  name: nextfit-service
  namespace: student-t-mittermayr
spec:
  selector:
    app: nextfit
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextfit-ingress
  namespace: student-t-mittermayr
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /nextfit/(.*)$
            pathType: Prefix
            backend:
              service:
                name: nextfit-service
                port:
                  number: 8080
